<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net6.0-windows;net472</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <!-- <Nullable>enable</Nullable> -->
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\res\icon.ico</ApplicationIcon>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>BinaryReceptorWinGui</RootNamespace>
    <TargetName>BinaryReceptorGUI</TargetName>
  </PropertyGroup>

   <ItemGroup>
    <None Update="..\..\res\icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="..\..\res\icon.ico" />
  </ItemGroup>
</Project>